-- +goose Up
ALTER TABLE accounts
  ADD COLUMN account_type text NOT NULL DEFAULT 'dealer',
  ADD COLUMN archived_at timestamptz,
  ADD COLUMN deleted_at timestamptz,
  ADD CONSTRAINT accounts_account_type_check CHECK (account_type IN ('dealer', 'customer', 'internal', 'support_provider'));

CREATE TABLE users (
  user_id text PRIMARY KEY,
  cognito_sub text NOT NULL UNIQUE,
  email text NOT NULL,
  email_normalized text NOT NULL UNIQUE,
  display_name text,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled', 'deleted'))
);

CREATE TABLE roles (
  role_id text PRIMARY KEY,
  account_id text REFERENCES accounts(account_id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz
);

CREATE UNIQUE INDEX roles_system_name_unique ON roles(name) WHERE account_id IS NULL;
CREATE UNIQUE INDEX roles_account_name_unique ON roles(account_id, name) WHERE account_id IS NOT NULL;

CREATE TABLE role_permissions (
  role_permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id text NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (role_id, action)
);

CREATE TABLE account_memberships (
  account_membership_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role_id text NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  CONSTRAINT account_memberships_status_check CHECK (status IN ('active', 'invited', 'disabled', 'removed')),
  UNIQUE (account_id, user_id)
);

CREATE INDEX account_memberships_user_id_idx ON account_memberships(user_id);
CREATE INDEX account_memberships_status_idx ON account_memberships(status);

CREATE TABLE customer_records (
  customer_record_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  display_name text NOT NULL,
  email text,
  email_normalized text,
  phone text,
  notes text,
  service_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  CONSTRAINT customer_records_status_check CHECK (status IN ('active', 'archived', 'inactive'))
);

CREATE INDEX customer_records_account_id_idx ON customer_records(account_id);
CREATE INDEX customer_records_email_normalized_idx ON customer_records(email_normalized);

ALTER TABLE sites
  ADD COLUMN customer_record_id text REFERENCES customer_records(customer_record_id) ON DELETE SET NULL,
  ADD COLUMN site_category text,
  ADD COLUMN service_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN archived_at timestamptz,
  ADD COLUMN deleted_at timestamptz,
  ADD CONSTRAINT sites_site_category_check CHECK (site_category IS NULL OR site_category IN ('residential', 'business', 'other'));

CREATE INDEX sites_customer_record_id_idx ON sites(customer_record_id);
CREATE INDEX sites_archived_at_idx ON sites(archived_at);

CREATE TABLE site_relationships (
  site_relationship_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  relationship_type text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  created_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT site_relationships_type_check CHECK (relationship_type IN ('owner', 'manager', 'support_provider')),
  CONSTRAINT site_relationships_status_check CHECK (status IN ('active', 'ended', 'revoked'))
);

CREATE UNIQUE INDEX site_relationships_one_active_owner_idx ON site_relationships(site_id) WHERE relationship_type = 'owner' AND status = 'active';
CREATE INDEX site_relationships_account_id_idx ON site_relationships(account_id);
CREATE INDEX site_relationships_site_status_idx ON site_relationships(site_id, status);

CREATE TABLE buildings (
  building_id text PRIMARY KEY,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  display_name text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  CONSTRAINT buildings_status_check CHECK (status IN ('active', 'archived'))
);

CREATE INDEX buildings_site_id_idx ON buildings(site_id);
CREATE UNIQUE INDEX buildings_one_default_per_site_idx ON buildings(site_id) WHERE is_default AND archived_at IS NULL;

CREATE TABLE zones (
  zone_id text PRIMARY KEY,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE CASCADE,
  building_id text NOT NULL REFERENCES buildings(building_id) ON DELETE CASCADE,
  display_name text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  CONSTRAINT zones_status_check CHECK (status IN ('active', 'archived'))
);

CREATE INDEX zones_site_id_idx ON zones(site_id);
CREATE INDEX zones_building_id_idx ON zones(building_id);
CREATE UNIQUE INDEX zones_one_default_per_building_idx ON zones(building_id) WHERE is_default AND archived_at IS NULL;

CREATE TABLE resources (
  resource_id text PRIMARY KEY,
  account_id text REFERENCES accounts(account_id) ON DELETE CASCADE,
  site_id text REFERENCES sites(site_id) ON DELETE CASCADE,
  resource_type text NOT NULL,
  parent_resource_id text REFERENCES resources(resource_id) ON DELETE SET NULL,
  display_name text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz,
  deleted_at timestamptz,
  CONSTRAINT resources_type_check CHECK (resource_type IN ('account', 'site', 'building', 'zone', 'device')),
  CONSTRAINT resources_status_check CHECK (status IN ('active', 'archived', 'deleted'))
);

CREATE INDEX resources_account_id_idx ON resources(account_id);
CREATE INDEX resources_site_id_idx ON resources(site_id);
CREATE INDEX resources_parent_resource_id_idx ON resources(parent_resource_id);

CREATE TABLE access_grants (
  access_grant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type text NOT NULL,
  subject_id text NOT NULL,
  resource_id text NOT NULL REFERENCES resources(resource_id) ON DELETE CASCADE,
  role_id text NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
  inheritance_mode text NOT NULL DEFAULT 'inherit',
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  revoked_at timestamptz,
  CONSTRAINT access_grants_subject_type_check CHECK (subject_type IN ('user', 'account', 'service_account')),
  CONSTRAINT access_grants_inheritance_mode_check CHECK (inheritance_mode IN ('inherit', 'direct_only')),
  CONSTRAINT access_grants_status_check CHECK (status IN ('active', 'revoked', 'expired'))
);

CREATE INDEX access_grants_subject_idx ON access_grants(subject_type, subject_id, status);
CREATE INDEX access_grants_resource_id_idx ON access_grants(resource_id);

ALTER TABLE devices
  ADD COLUMN installation_id text,
  ADD COLUMN claim_state text NOT NULL DEFAULT 'CLAIMED',
  ADD COLUMN zone_id text REFERENCES zones(zone_id) ON DELETE SET NULL,
  ADD COLUMN revoked_at timestamptz,
  ADD CONSTRAINT devices_claim_state_check CHECK (claim_state IN ('CLAIMED', 'REVOKED')),
  ADD CONSTRAINT devices_iot_thing_matches_device_id_check CHECK (iot_thing_name IS NULL OR iot_thing_name = device_id);

CREATE INDEX devices_zone_id_idx ON devices(zone_id);
CREATE UNIQUE INDEX devices_active_installation_idx ON devices(installation_id) WHERE installation_id IS NOT NULL AND revoked_at IS NULL;

ALTER TABLE device_credentials
  ADD COLUMN aws_region text,
  ADD COLUMN iot_endpoint text,
  ADD COLUMN iot_thing_name text,
  ADD COLUMN certificate_id text,
  ADD COLUMN certificate_arn text,
  ADD COLUMN principal_identifier text,
  ADD COLUMN credential_slot text NOT NULL DEFAULT 'primary',
  ADD COLUMN issued_at timestamptz,
  ADD CONSTRAINT device_credentials_slot_check CHECK (credential_slot IN ('primary', 'secondary'));

CREATE UNIQUE INDEX device_credentials_certificate_id_unique ON device_credentials(certificate_id) WHERE certificate_id IS NOT NULL;
CREATE INDEX device_credentials_principal_identifier_idx ON device_credentials(principal_identifier);
CREATE INDEX device_credentials_iot_thing_name_idx ON device_credentials(iot_thing_name);

CREATE TABLE device_claim_invites (
  claim_invite_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE RESTRICT,
  customer_record_id text REFERENCES customer_records(customer_record_id) ON DELETE SET NULL,
  created_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  created_by_membership_id bigint REFERENCES account_memberships(account_membership_id) ON DELETE SET NULL,
  recipient_email_normalized text,
  recipient_email_hash text,
  claim_code_hash text NOT NULL UNIQUE,
  claim_code_fingerprint text NOT NULL,
  display_snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  display_snapshot_hash text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  intended_action text NOT NULL DEFAULT 'fresh_claim',
  email_delivery_status text NOT NULL DEFAULT 'NOT_REQUESTED',
  email_last_attempt_at timestamptz,
  email_last_provider_message_id text,
  email_failure_reason text,
  verification_attempt_count integer NOT NULL DEFAULT 0,
  confirmed_verification_id text,
  used_by_device_id text REFERENCES devices(device_id) ON DELETE SET NULL,
  replaced_by_claim_invite_id text REFERENCES device_claim_invites(claim_invite_id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  cancelled_at timestamptz,
  cancelled_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT device_claim_invites_status_check CHECK (status IN ('OPEN', 'USED', 'EXPIRED', 'CANCELLED', 'FAILED')),
  CONSTRAINT device_claim_invites_intended_action_check CHECK (intended_action IN ('fresh_claim', 'repair_existing_device', 'reconnect_existing_device')),
  CONSTRAINT device_claim_invites_email_status_check CHECK (email_delivery_status IN ('NOT_REQUESTED', 'QUEUED', 'SENT', 'FAILED'))
);

CREATE INDEX device_claim_invites_site_status_idx ON device_claim_invites(site_id, status);
CREATE INDEX device_claim_invites_expires_at_idx ON device_claim_invites(expires_at);
CREATE INDEX device_claim_invites_recipient_hash_idx ON device_claim_invites(recipient_email_hash);

CREATE TABLE device_claim_verifications (
  claim_verification_id text PRIMARY KEY,
  claim_invite_id text NOT NULL REFERENCES device_claim_invites(claim_invite_id) ON DELETE CASCADE,
  installation_id text NOT NULL,
  agent_version text,
  recognition_signals jsonb NOT NULL DEFAULT '{}'::jsonb,
  csr_sha256 text NOT NULL,
  verification_token_hash text NOT NULL,
  presented_details_hash text NOT NULL,
  source_ip_hash text,
  user_agent_hash text,
  confirmed_device_id text REFERENCES devices(device_id) ON DELETE SET NULL,
  failure_reason text,
  status text NOT NULL DEFAULT 'PRESENTED',
  expires_at timestamptz NOT NULL,
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT device_claim_verifications_status_check CHECK (status IN ('PRESENTED', 'CONFIRMED', 'AWS_PROVISIONING_ISSUED', 'CLAIMED', 'EXPIRED', 'REVOKED', 'FAILED'))
);

CREATE INDEX device_claim_verifications_invite_status_idx ON device_claim_verifications(claim_invite_id, status);
CREATE INDEX device_claim_verifications_installation_idx ON device_claim_verifications(installation_id);
CREATE UNIQUE INDEX device_claim_verifications_active_installation_idx
  ON device_claim_verifications(claim_invite_id, installation_id)
  WHERE status IN ('PRESENTED', 'CONFIRMED', 'AWS_PROVISIONING_ISSUED');

CREATE TABLE device_claim_invite_email_deliveries (
  email_delivery_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_invite_id text NOT NULL REFERENCES device_claim_invites(claim_invite_id) ON DELETE CASCADE,
  recipient_email_hash text NOT NULL,
  provider text NOT NULL,
  provider_message_id text,
  status text NOT NULL DEFAULT 'QUEUED',
  attempt_number integer NOT NULL DEFAULT 1,
  failure_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  failed_at timestamptz,
  CONSTRAINT device_claim_invite_email_deliveries_status_check CHECK (status IN ('QUEUED', 'SENT', 'FAILED', 'BOUNCED', 'SUPPRESSED'))
);

CREATE INDEX device_claim_invite_email_deliveries_invite_idx ON device_claim_invite_email_deliveries(claim_invite_id);
CREATE INDEX device_claim_invite_email_deliveries_recipient_hash_idx ON device_claim_invite_email_deliveries(recipient_email_hash);

CREATE TABLE audit_events (
  audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_subject_type text NOT NULL,
  actor_subject_id text NOT NULL,
  action text NOT NULL,
  target_resource_id text REFERENCES resources(resource_id) ON DELETE SET NULL,
  result text NOT NULL,
  account_id text REFERENCES accounts(account_id) ON DELETE SET NULL,
  site_id text REFERENCES sites(site_id) ON DELETE SET NULL,
  device_id text REFERENCES devices(device_id) ON DELETE SET NULL,
  request_id text,
  ip_address_hash text,
  user_agent_hash text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_events_result_check CHECK (result IN ('success', 'denied', 'failed'))
);

CREATE INDEX audit_events_action_created_idx ON audit_events(action, created_at DESC);
CREATE INDEX audit_events_actor_created_idx ON audit_events(actor_subject_type, actor_subject_id, created_at DESC);
CREATE INDEX audit_events_scope_created_idx ON audit_events(account_id, site_id, device_id, created_at DESC);

CREATE TABLE commands (
  command_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE RESTRICT,
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  command_type text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  idempotency_key text,
  requested_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ack_deadline_at timestamptz NOT NULL,
  result_deadline_at timestamptz NOT NULL,
  queued_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  acked_at timestamptz,
  terminal_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT commands_status_check CHECK (status IN ('queued', 'sent', 'ack_accepted', 'ack_rejected', 'ack_timed_out', 'running', 'succeeded', 'failed', 'timed_out', 'canceled'))
);

CREATE INDEX commands_device_status_idx ON commands(device_id, status);
CREATE INDEX commands_site_created_idx ON commands(site_id, created_at DESC);
CREATE UNIQUE INDEX commands_idempotency_key_unique ON commands(account_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE TABLE command_progress_events (
  command_progress_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_id text NOT NULL REFERENCES commands(command_id) ON DELETE CASCADE,
  phase text NOT NULL,
  reason_code text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  reported_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX command_progress_events_command_received_idx ON command_progress_events(command_id, received_at);

CREATE TABLE command_results (
  command_result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_id text NOT NULL REFERENCES commands(command_id) ON DELETE CASCADE,
  status text NOT NULL,
  result_type text NOT NULL,
  reason_code text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz,
  finished_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT command_results_status_check CHECK (status IN ('succeeded', 'failed', 'timed_out', 'canceled'))
);

CREATE UNIQUE INDEX command_results_one_terminal_idx ON command_results(command_id);

CREATE TABLE device_desired_state (
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  state_key text NOT NULL,
  desired_version text NOT NULL,
  desired_json jsonb NOT NULL,
  convergence_status text NOT NULL DEFAULT 'pending',
  convergence_deadline_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (device_id, state_key),
  CONSTRAINT device_desired_state_convergence_status_check CHECK (convergence_status IN ('pending', 'converged', 'late', 'failed', 'unknown'))
);

CREATE TABLE device_edge_state_projection (
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  projection_key text NOT NULL,
  desired_version text,
  reported_version text,
  projection_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  convergence_status text NOT NULL DEFAULT 'unknown',
  last_reported_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (device_id, projection_key),
  CONSTRAINT device_edge_state_projection_convergence_status_check CHECK (convergence_status IN ('pending', 'converged', 'late', 'failed', 'unknown'))
);

INSERT INTO roles (role_id, name, description, is_system)
VALUES
  ('role_owner', 'owner', 'System owner role with all seeded permissions.', true),
  ('role_admin', 'admin', 'System administrator role for day-to-day account and site management.', true),
  ('role_operator', 'operator', 'System operator role for operational site and device workflows.', true),
  ('role_viewer', 'viewer', 'System viewer role for read-only account and site access.', true);

INSERT INTO role_permissions (role_id, action)
SELECT 'role_owner', action
FROM (VALUES
  ('account:view'), ('account:update'), ('account:delete'),
  ('member:view'), ('member:invite'), ('member:update_role'), ('member:manage_owner'), ('member:remove'),
  ('role:view'), ('role:create'), ('role:update'), ('role:delete'),
  ('site:view'), ('site:create'), ('site:update'), ('site:delete'), ('site:archive'), ('site:relationship_manage'),
  ('customer_record:view'), ('customer_record:create'), ('customer_record:update'),
  ('building:view'), ('building:create'), ('building:update'), ('building:delete'),
  ('zone:view'), ('zone:create'), ('zone:update'), ('zone:delete'),
  ('device:view'), ('device:update'), ('device:refresh'), ('device:diagnose'), ('device:command'),
  ('device_claim_invite:view'), ('device_claim_invite:create'), ('device_claim_invite:cancel'), ('device_claim_invite:replace'),
  ('agent:claim'), ('agent:release'), ('agent:update'), ('agent:restart'),
  ('host:reboot'), ('backup:trigger'), ('backup:restore'), ('diagnostics:request'),
  ('remote_access:view'), ('remote_access:update'),
  ('telemetry:view'), ('topology:view'),
  ('alert:view'), ('alert:acknowledge'), ('alert_recipient:view'), ('alert_recipient:manage'),
  ('billing:view'), ('billing:manage'), ('audit:view'),
  ('support:grant'), ('support:access'),
  ('service_account:view'), ('service_account:create'), ('service_account:update'), ('service_account:delete'),
  ('api_key:create'), ('api_key:revoke')
) AS actions(action);

INSERT INTO role_permissions (role_id, action)
SELECT 'role_admin', action
FROM (VALUES
  ('account:view'), ('account:update'),
  ('member:view'), ('member:invite'), ('member:update_role'), ('member:remove'),
  ('role:view'), ('site:view'), ('site:create'), ('site:update'), ('site:archive'), ('site:relationship_manage'),
  ('customer_record:view'), ('customer_record:create'), ('customer_record:update'),
  ('building:view'), ('building:create'), ('building:update'),
  ('zone:view'), ('zone:create'), ('zone:update'),
  ('device:view'), ('device:update'), ('device:refresh'), ('device:diagnose'), ('device:command'),
  ('device_claim_invite:view'), ('device_claim_invite:create'), ('device_claim_invite:cancel'), ('device_claim_invite:replace'),
  ('agent:claim'), ('agent:release'), ('agent:update'), ('agent:restart'),
  ('backup:trigger'), ('diagnostics:request'),
  ('remote_access:view'), ('remote_access:update'),
  ('telemetry:view'), ('topology:view'),
  ('alert:view'), ('alert:acknowledge'), ('alert_recipient:view'), ('alert_recipient:manage'),
  ('billing:view'), ('audit:view'), ('service_account:view')
) AS actions(action);

INSERT INTO role_permissions (role_id, action)
SELECT 'role_operator', action
FROM (VALUES
  ('account:view'), ('member:view'), ('site:view'),
  ('customer_record:view'), ('building:view'), ('zone:view'),
  ('device:view'), ('device:refresh'), ('device:diagnose'), ('device:command'),
  ('device_claim_invite:view'), ('device_claim_invite:create'),
  ('backup:trigger'), ('diagnostics:request'),
  ('remote_access:view'), ('telemetry:view'), ('topology:view'),
  ('alert:view'), ('alert:acknowledge')
) AS actions(action);

INSERT INTO role_permissions (role_id, action)
SELECT 'role_viewer', action
FROM (VALUES
  ('account:view'), ('member:view'), ('site:view'), ('customer_record:view'),
  ('building:view'), ('zone:view'), ('device:view'), ('device_claim_invite:view'),
  ('remote_access:view'), ('telemetry:view'), ('topology:view'), ('alert:view'), ('billing:view')
) AS actions(action);

-- +goose Down
DELETE FROM role_permissions WHERE role_id IN ('role_owner', 'role_admin', 'role_operator', 'role_viewer');
DELETE FROM roles WHERE role_id IN ('role_owner', 'role_admin', 'role_operator', 'role_viewer');

DROP TABLE device_edge_state_projection;
DROP TABLE device_desired_state;
DROP TABLE command_results;
DROP TABLE command_progress_events;
DROP TABLE commands;
DROP TABLE audit_events;
DROP TABLE device_claim_invite_email_deliveries;
DROP TABLE device_claim_verifications;
DROP TABLE device_claim_invites;
DROP TABLE access_grants;
DROP TABLE resources;
DROP TABLE zones;
DROP TABLE buildings;
DROP TABLE site_relationships;

DROP INDEX IF EXISTS device_credentials_iot_thing_name_idx;
DROP INDEX IF EXISTS device_credentials_principal_identifier_idx;
DROP INDEX IF EXISTS device_credentials_certificate_id_unique;

ALTER TABLE device_credentials
  DROP CONSTRAINT device_credentials_slot_check,
  DROP COLUMN issued_at,
  DROP COLUMN credential_slot,
  DROP COLUMN principal_identifier,
  DROP COLUMN certificate_arn,
  DROP COLUMN certificate_id,
  DROP COLUMN iot_thing_name,
  DROP COLUMN iot_endpoint,
  DROP COLUMN aws_region;

DROP INDEX IF EXISTS devices_active_installation_idx;
DROP INDEX IF EXISTS devices_zone_id_idx;

ALTER TABLE devices
  DROP CONSTRAINT devices_iot_thing_matches_device_id_check,
  DROP CONSTRAINT devices_claim_state_check,
  DROP COLUMN revoked_at,
  DROP COLUMN zone_id,
  DROP COLUMN claim_state,
  DROP COLUMN installation_id;

ALTER TABLE sites
  DROP CONSTRAINT sites_site_category_check,
  DROP COLUMN deleted_at,
  DROP COLUMN archived_at,
  DROP COLUMN service_address,
  DROP COLUMN site_category,
  DROP COLUMN customer_record_id;

DROP TABLE customer_records;
DROP TABLE account_memberships;
DROP TABLE role_permissions;
DROP TABLE roles;
DROP TABLE users;

ALTER TABLE accounts
  DROP CONSTRAINT accounts_account_type_check,
  DROP COLUMN deleted_at,
  DROP COLUMN archived_at,
  DROP COLUMN account_type;
