-- +goose Up
CREATE TABLE alert_candidates (
  candidate_id text PRIMARY KEY,
  event_type text NOT NULL,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE RESTRICT,
  device_id text REFERENCES devices(device_id) ON DELETE CASCADE,
  source text NOT NULL,
  previous_state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  new_state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX alert_candidates_site_received_idx ON alert_candidates(site_id, received_at DESC);
CREATE INDEX alert_candidates_device_event_idx ON alert_candidates(device_id, event_type, occurred_at DESC) WHERE device_id IS NOT NULL;

CREATE TABLE alerts (
  alert_id text PRIMARY KEY,
  alert_key text NOT NULL,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE RESTRICT,
  device_id text REFERENCES devices(device_id) ON DELETE CASCADE,
  family text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  title text NOT NULL,
  detail text NOT NULL,
  reason_code text NOT NULL,
  first_candidate_id text REFERENCES alert_candidates(candidate_id) ON DELETE SET NULL,
  last_candidate_id text REFERENCES alert_candidates(candidate_id) ON DELETE SET NULL,
  occurrence_count integer NOT NULL DEFAULT 1,
  acknowledged_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  acknowledged_at timestamptz,
  snoozed_until timestamptz,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alerts_family_check CHECK (family IN ('device_disconnected', 'backup_failed', 'backup_overdue', 'app_update_attention')),
  CONSTRAINT alerts_severity_check CHECK (severity IN ('critical', 'warning', 'info')),
  CONSTRAINT alerts_status_check CHECK (status IN ('active', 'resolved')),
  CONSTRAINT alerts_occurrence_count_check CHECK (occurrence_count > 0)
);

CREATE UNIQUE INDEX alerts_one_active_key_idx ON alerts(alert_key) WHERE status = 'active';
CREATE INDEX alerts_site_status_idx ON alerts(site_id, status, severity, updated_at DESC);
CREATE INDEX alerts_device_status_idx ON alerts(device_id, status, updated_at DESC) WHERE device_id IS NOT NULL;

CREATE TABLE alert_events (
  alert_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id text NOT NULL REFERENCES alerts(alert_id) ON DELETE CASCADE,
  candidate_id text REFERENCES alert_candidates(candidate_id) ON DELETE SET NULL,
  event_type text NOT NULL,
  actor_subject_type text NOT NULL DEFAULT 'system',
  actor_subject_id text NOT NULL DEFAULT 'system',
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alert_events_type_check CHECK (event_type IN ('created', 'updated', 'resolved', 'acknowledged', 'snoozed'))
);

CREATE INDEX alert_events_alert_created_idx ON alert_events(alert_id, created_at DESC);

-- +goose Down
DROP INDEX IF EXISTS alert_events_alert_created_idx;
DROP TABLE IF EXISTS alert_events;
DROP INDEX IF EXISTS alerts_device_status_idx;
DROP INDEX IF EXISTS alerts_site_status_idx;
DROP INDEX IF EXISTS alerts_one_active_key_idx;
DROP TABLE IF EXISTS alerts;
DROP INDEX IF EXISTS alert_candidates_device_event_idx;
DROP INDEX IF EXISTS alert_candidates_site_received_idx;
DROP TABLE IF EXISTS alert_candidates;
