-- +goose Up
CREATE TABLE release_channels (
  channel_key text PRIMARY KEY,
  cloud_environment text NOT NULL,
  release_track text NOT NULL,
  ha_app_slug text NOT NULL,
  repository_url text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  internal_only boolean NOT NULL DEFAULT false,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT release_channels_key_check CHECK (channel_key IN ('stable', 'candidate', 'staging', 'dev')),
  CONSTRAINT release_channels_environment_check CHECK (cloud_environment IN ('production', 'staging')),
  CONSTRAINT release_channels_track_check CHECK (release_track IN ('stable', 'candidate', 'staging', 'dev')),
  CONSTRAINT release_channels_status_check CHECK (status IN ('active', 'disabled')),
  CONSTRAINT release_channels_assignment_check CHECK (
    (channel_key IN ('stable', 'candidate') AND cloud_environment = 'production' AND release_track = channel_key AND internal_only = false)
    OR (channel_key = 'staging' AND cloud_environment = 'staging' AND release_track = 'staging')
    OR (channel_key = 'dev' AND cloud_environment = 'staging' AND release_track = 'dev' AND internal_only = true)
  )
);

CREATE UNIQUE INDEX release_channels_environment_track_idx ON release_channels(cloud_environment, release_track);

CREATE TABLE release_artifacts (
  release_artifact_id text PRIMARY KEY,
  channel_key text NOT NULL REFERENCES release_channels(channel_key) ON DELETE RESTRICT,
  version text NOT NULL,
  cloud_environment text NOT NULL,
  release_track text NOT NULL,
  ha_app_slug text NOT NULL,
  source_commit_sha text NOT NULL,
  image_ref text NOT NULL,
  image_digest text NOT NULL,
  package_digest text,
  config_digest text,
  status text NOT NULL DEFAULT 'draft',
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  published_at timestamptz,
  retired_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT release_artifacts_environment_check CHECK (cloud_environment IN ('production', 'staging')),
  CONSTRAINT release_artifacts_track_check CHECK (release_track IN ('stable', 'candidate', 'staging', 'dev')),
  CONSTRAINT release_artifacts_status_check CHECK (status IN ('draft', 'published', 'retired', 'unsupported')),
  CONSTRAINT release_artifacts_image_digest_check CHECK (image_digest LIKE 'sha256:%')
);

CREATE UNIQUE INDEX release_artifacts_channel_version_idx ON release_artifacts(channel_key, version);
CREATE UNIQUE INDEX release_artifacts_channel_image_digest_idx ON release_artifacts(channel_key, image_digest);
CREATE INDEX release_artifacts_channel_status_idx ON release_artifacts(channel_key, status, created_at DESC);

CREATE TABLE release_compatibility_windows (
  release_compatibility_window_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_artifact_id text NOT NULL REFERENCES release_artifacts(release_artifact_id) ON DELETE CASCADE,
  min_agent_protocol text,
  max_agent_protocol text,
  min_ha_version text,
  max_ha_version text,
  support_status text NOT NULL DEFAULT 'supported',
  reason_code text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT release_compatibility_windows_status_check CHECK (support_status IN ('supported', 'unsupported'))
);

CREATE INDEX release_compatibility_windows_artifact_idx ON release_compatibility_windows(release_artifact_id);

-- +goose Down
DROP INDEX IF EXISTS release_compatibility_windows_artifact_idx;
DROP TABLE IF EXISTS release_compatibility_windows;
DROP INDEX IF EXISTS release_artifacts_channel_status_idx;
DROP INDEX IF EXISTS release_artifacts_channel_image_digest_idx;
DROP INDEX IF EXISTS release_artifacts_channel_version_idx;
DROP TABLE IF EXISTS release_artifacts;
DROP INDEX IF EXISTS release_channels_environment_track_idx;
DROP TABLE IF EXISTS release_channels;
