-- +goose Up
CREATE TABLE alert_recipients (
  alert_recipient_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  site_id text REFERENCES sites(site_id) ON DELETE CASCADE,
  email text NOT NULL,
  email_normalized text NOT NULL,
  display_label text,
  channel text NOT NULL DEFAULT 'email',
  status text NOT NULL DEFAULT 'pending_verification',
  created_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  verified_at timestamptz,
  disabled_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alert_recipients_channel_check CHECK (channel IN ('email')),
  CONSTRAINT alert_recipients_status_check CHECK (status IN ('pending_verification', 'verified', 'disabled', 'deleted'))
);

CREATE UNIQUE INDEX alert_recipients_account_email_global_idx
  ON alert_recipients(account_id, email_normalized)
  WHERE site_id IS NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX alert_recipients_account_site_email_idx
  ON alert_recipients(account_id, site_id, email_normalized)
  WHERE site_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX alert_recipients_account_status_idx ON alert_recipients(account_id, status, updated_at DESC);
CREATE INDEX alert_recipients_site_status_idx ON alert_recipients(site_id, status, updated_at DESC) WHERE site_id IS NOT NULL;

CREATE TABLE alert_recipient_subscriptions (
  alert_recipient_subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_recipient_id text NOT NULL REFERENCES alert_recipients(alert_recipient_id) ON DELETE CASCADE,
  family text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alert_recipient_subscriptions_family_check CHECK (family IN ('device_disconnected', 'backup_failed_or_overdue', 'app_update_attention')),
  UNIQUE (alert_recipient_id, family)
);

CREATE INDEX alert_recipient_subscriptions_family_idx ON alert_recipient_subscriptions(family, enabled);

-- +goose Down
DROP INDEX IF EXISTS alert_recipient_subscriptions_family_idx;
DROP TABLE IF EXISTS alert_recipient_subscriptions;
DROP INDEX IF EXISTS alert_recipients_site_status_idx;
DROP INDEX IF EXISTS alert_recipients_account_status_idx;
DROP INDEX IF EXISTS alert_recipients_account_site_email_idx;
DROP INDEX IF EXISTS alert_recipients_account_email_global_idx;
DROP TABLE IF EXISTS alert_recipients;
