-- +goose Up
CREATE TABLE rollouts (
  rollout_id text PRIMARY KEY,
  channel_key text NOT NULL REFERENCES release_channels(channel_key) ON DELETE RESTRICT,
  target_release_artifact_id text REFERENCES release_artifacts(release_artifact_id) ON DELETE RESTRICT,
  target_version text NOT NULL,
  target_type text NOT NULL,
  cohort_key text,
  status text NOT NULL DEFAULT 'draft',
  created_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  reason_code text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  activated_at timestamptz,
  completed_at timestamptz,
  canceled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rollouts_target_type_check CHECK (target_type IN ('device', 'cohort')),
  CONSTRAINT rollouts_status_check CHECK (status IN ('draft', 'active', 'paused', 'completed', 'canceled')),
  CONSTRAINT rollouts_cohort_key_check CHECK (
    (target_type = 'cohort' AND cohort_key IS NOT NULL)
    OR (target_type = 'device')
  )
);

CREATE INDEX rollouts_channel_status_idx ON rollouts(channel_key, status, created_at DESC);
CREATE INDEX rollouts_target_artifact_idx ON rollouts(target_release_artifact_id) WHERE target_release_artifact_id IS NOT NULL;

CREATE TABLE device_update_assignments (
  device_update_assignment_id text PRIMARY KEY,
  rollout_id text NOT NULL REFERENCES rollouts(rollout_id) ON DELETE RESTRICT,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text NOT NULL REFERENCES sites(site_id) ON DELETE RESTRICT,
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  channel_key text NOT NULL REFERENCES release_channels(channel_key) ON DELETE RESTRICT,
  desired_version text NOT NULL,
  edge_desired_version text NOT NULL,
  status text NOT NULL DEFAULT 'assigned',
  reason_code text,
  assigned_by_user_id text REFERENCES users(user_id) ON DELETE SET NULL,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  projected_at timestamptz,
  converged_at timestamptz,
  failed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT device_update_assignments_status_check CHECK (status IN ('assigned', 'projected', 'projection_failed', 'converged', 'failed', 'canceled')),
  UNIQUE (rollout_id, device_id)
);

CREATE UNIQUE INDEX device_update_assignments_one_open_idx
  ON device_update_assignments(device_id)
  WHERE status IN ('assigned', 'projected', 'projection_failed');

CREATE INDEX device_update_assignments_site_status_idx ON device_update_assignments(site_id, status, updated_at DESC);
CREATE INDEX device_update_assignments_rollout_status_idx ON device_update_assignments(rollout_id, status);

CREATE TABLE rollout_audit_events (
  rollout_audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rollout_id text NOT NULL REFERENCES rollouts(rollout_id) ON DELETE CASCADE,
  device_update_assignment_id text REFERENCES device_update_assignments(device_update_assignment_id) ON DELETE SET NULL,
  actor_subject_type text NOT NULL,
  actor_subject_id text NOT NULL,
  action text NOT NULL,
  result text NOT NULL,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rollout_audit_events_result_check CHECK (result IN ('success', 'denied', 'failed'))
);

CREATE INDEX rollout_audit_events_rollout_created_idx ON rollout_audit_events(rollout_id, created_at DESC);

-- +goose Down
DROP INDEX IF EXISTS rollout_audit_events_rollout_created_idx;
DROP TABLE IF EXISTS rollout_audit_events;
DROP INDEX IF EXISTS device_update_assignments_rollout_status_idx;
DROP INDEX IF EXISTS device_update_assignments_site_status_idx;
DROP INDEX IF EXISTS device_update_assignments_one_open_idx;
DROP TABLE IF EXISTS device_update_assignments;
DROP INDEX IF EXISTS rollouts_target_artifact_idx;
DROP INDEX IF EXISTS rollouts_channel_status_idx;
DROP TABLE IF EXISTS rollouts;
