-- +goose Up
CREATE TABLE accounts (
  account_id text PRIMARY KEY,
  display_name text,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sites (
  site_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  display_name text,
  time_zone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sites_account_id_idx ON sites(account_id);

CREATE TABLE devices (
  device_id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES accounts(account_id) ON DELETE RESTRICT,
  site_id text REFERENCES sites(site_id) ON DELETE SET NULL,
  iot_thing_name text UNIQUE,
  lifecycle_status text NOT NULL DEFAULT 'registered',
  claimed_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX devices_account_id_idx ON devices(account_id);
CREATE INDEX devices_site_id_idx ON devices(site_id);
CREATE INDEX devices_lifecycle_status_idx ON devices(lifecycle_status);

CREATE TABLE device_credentials (
  credential_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  certificate_fingerprint text NOT NULL UNIQUE,
  certificate_serial text,
  certificate_issuer text,
  status text NOT NULL DEFAULT 'active',
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (certificate_issuer, certificate_serial)
);

CREATE INDEX device_credentials_device_id_idx ON device_credentials(device_id);
CREATE INDEX device_credentials_status_idx ON device_credentials(status);

CREATE TABLE device_presence (
  device_id text PRIMARY KEY REFERENCES devices(device_id) ON DELETE CASCADE,
  connection_state text NOT NULL DEFAULT 'unknown',
  last_client_id text,
  last_session_identifier text,
  last_connected_at timestamptz,
  last_disconnected_at timestamptz,
  last_seen_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX device_presence_connection_state_idx ON device_presence(connection_state);
CREATE INDEX device_presence_last_seen_at_idx ON device_presence(last_seen_at DESC);

CREATE TABLE device_lifecycle_events (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text REFERENCES devices(device_id) ON DELETE SET NULL,
  client_id text,
  certificate_fingerprint text,
  event_type text NOT NULL,
  session_identifier text,
  observed_at timestamptz NOT NULL,
  raw_event jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX device_lifecycle_events_device_observed_idx ON device_lifecycle_events(device_id, observed_at DESC);
CREATE INDEX device_lifecycle_events_client_observed_idx ON device_lifecycle_events(client_id, observed_at DESC);
CREATE INDEX device_lifecycle_events_event_type_idx ON device_lifecycle_events(event_type);

CREATE TABLE device_latest_state (
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  message_type text NOT NULL,
  schema_type text NOT NULL,
  schema_version integer NOT NULL,
  message_id text NOT NULL,
  observed_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL,
  material_hash text NOT NULL,
  material jsonb NOT NULL,
  sidecar jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (device_id, message_type, schema_type, schema_version)
);

CREATE INDEX device_latest_state_observed_at_idx ON device_latest_state(observed_at DESC);
CREATE INDEX device_latest_state_material_hash_idx ON device_latest_state(material_hash);

CREATE TABLE device_telemetry_events (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  message_id text NOT NULL,
  message_type text NOT NULL,
  schema_type text NOT NULL,
  schema_version integer NOT NULL,
  observed_at timestamptz NOT NULL,
  received_at timestamptz NOT NULL,
  material_hash text NOT NULL,
  material jsonb NOT NULL,
  sidecar jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (device_id, message_id)
);

CREATE INDEX device_telemetry_events_device_observed_idx ON device_telemetry_events(device_id, observed_at DESC);
CREATE INDEX device_telemetry_events_schema_observed_idx ON device_telemetry_events(schema_type, schema_version, observed_at DESC);
CREATE INDEX device_telemetry_events_material_hash_idx ON device_telemetry_events(material_hash);

CREATE TABLE telemetry_ingest_failures (
  failure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id text,
  message_id text,
  schema_type text,
  stage text NOT NULL,
  reason text NOT NULL,
  received_at timestamptz NOT NULL,
  raw_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX telemetry_ingest_failures_received_at_idx ON telemetry_ingest_failures(received_at DESC);
CREATE INDEX telemetry_ingest_failures_device_received_idx ON telemetry_ingest_failures(device_id, received_at DESC);
CREATE INDEX telemetry_ingest_failures_stage_idx ON telemetry_ingest_failures(stage);

-- +goose Down
DROP TABLE telemetry_ingest_failures;
DROP TABLE device_telemetry_events;
DROP TABLE device_latest_state;
DROP TABLE device_lifecycle_events;
DROP TABLE device_presence;
DROP TABLE device_credentials;
DROP TABLE devices;
DROP TABLE sites;
DROP TABLE accounts;
